---
- name: Assert variables are defined
  ansible.builtin.assert:
    that:
      - ansible_user == 'root'
      - tmproot_mutex is defined
      - tmproot_tmproot is defined
      - tmproot_device is defined
      - tmproot_device is match('^/dev/\w+$')

- name: Get tmproot state
  ansible.builtin.stat:
    path: "{{ tmproot_mutex }}"
  register: tmproot_mutex_state

- name: Mount root
  ansible.builtin.include_tasks: 00-mount.yml
  when: tmproot_mutex_state.stat.exists
