---
- name: terminate rest processes
  ansible.builtin.shell: |
    for i in $(lsof | grep /oldroot | awk '{print $2}' | sort -u); do kill -9 $i; done

- name: pause for 5 seconds
  ansible.builtin.pause:
    seconds: 5

- name: unmount oldroot uefi
  ansible.builtin.mount:
    path: "/oldroot/boot/efi"
    state: unmounted
  ignore_errors: true

- name: unmount oldroot
  ansible.builtin.mount:
    path: "/oldroot"
    state: unmounted
  ignore_errors: true

- name: wait for oldroot to be unmounted
  ansible.builtin.wait_for:
    path: /oldroot/bin
    state: absent
    timeout: 15
