---
- name: update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: install debootstrap
  ansible.builtin.apt:
    name: debootstrap
    state: present
    install_recommends: false

- name: create rootfs folder
  ansible.builtin.file:
    path: "{{ volume_shrink_rootfs }}"
    state: directory

- name: mount tmpfs
  ansible.builtin.mount:
    path: "{{ volume_shrink_rootfs }}"
    src: none
    fstype: tmpfs
    state: mounted

- name: create rootfs
  ansible.builtin.command: debootstrap --variant=minbase bullseye {{ volume_shrink_rootfs }} https://deb.debian.org/debian/
  args:
    creates: "{{ volume_shrink_rootfs }}/bin"

- name: create rootfs dir structure
  ansible.builtin.file:
    path: "{{ volume_shrink_rootfs }}/{{ item }}"
    state: directory
  loop:
    - dev
    - proc
    - run
    - sys
    - tmp
    - usr
    - var
    - oldroot

- name: list running sockets
  ansible.builtin.shell: systemctl | grep running | grep socket | awk '{print $1}'
  changed_when: false
  register: running_sockets

- name: stop running sockets
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  loop: "{{ running_sockets.stdout_lines }}"

- name: list running services
  ansible.builtin.shell: systemctl | grep running | grep service | grep -v 'ssh.service' | awk '{print $1}'
  changed_when: false
  register: running_services

- name: stop running services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  loop: "{{ running_services.stdout_lines }}"
