---
- name: set tmproot state
  ansible.builtin.stat:
    path: /var/lock/tmproot
  register: tmproot

- name: include tmproot
  include_tasks: 00-tmproot.yml
  when: not tmproot.stat.exists

- name: include unmount
  include_tasks: 01-unmount.yml

- include_tasks: 02-resize.yml
