---
- name: set state
  ansible.builtin.stat:
    path: /var/lock/volume-rootfs-private
  register: lock_rootfs

- name: include rootfs
  include_tasks: 01-rootfs.yml
  when: not lock_rootfs.stat.exists
