galaxy_info:
  author: Andrey Gubarev <andrey@andreygubarev.com> (andreygubarev.com)
  description: Ansible Role to mount tmpfs on /
  company: andreygubarev

  license: MIT

  min_ansible_version: '7.0.0'

  platforms:
  - name: Debian
    versions:
    - bookworm

  galaxy_tags: []

dependencies: []
