---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install fdisk utility if not present
  ansible.builtin.apt:
    name:
      - fdisk
      - parted
    state: present

- name: Read device information (always use unit when probing)
  community.general.parted:
    device: "{{ freespace_allocation_device }}"
    unit: MB
  register: freespace_allocation_device_info

- name: Calculate the available contiguous free space
  ansible.builtin.set_fact:
    freespace_allocation_space_available: "{{ (freespace_allocation_device_info.disk.size - freespace_allocation_device_info.partitions[-1]['end']) | round(2, 'floor') }}"

- name: Create a new partition
  when: freespace_allocation_space_available | int > freespace_allocation_space_minimal | int
  block:
    - name: Create a new partition using fdisk
      ansible.builtin.shell: |
        set -euo pipefail
        echo -e "n\n\n\n\nw" | fdisk /dev/vdb | grep 'Created a new partition' | awk '{print $5}'
      changed_when: true
      register: freespace_allocation_partition
      args:
        executable: /bin/bash

    - name: Print the new partition information
      ansible.builtin.debug:
        msg: "Created a new partition: {{ freespace_allocation_device }}{{ freespace_allocation_partition.stdout }}"
