---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install fdisk utility if not present
  ansible.builtin.apt:
    name:
      - fdisk
      - parted
    state: present

- name: Read device information (always use unit when probing)
  community.general.parted:
    device: "{{ freespace_allocation_device }}"
    unit: MB
  register: freespace_allocation_device_info

- name: Calculate the available contiguous free space
  ansible.builtin.set_fact:
    freespace_allocation_space_available: "{{ (freespace_allocation_device_info.disk.size - freespace_allocation_device_info.partitions[-1]['end']) | round(2, 'floor')  }}"

- name: "Assert that free space is greater than {{ freespace_allocation_space_required }}MB"
  ansible.builtin.assert:
    that:
      - freespace_allocation_space_available | int > freespace_allocation_space_required | int
    fail_msg: "Not enough free space on {{ freespace_allocation_device }} to create a partition"
    success_msg: "Enough free space on {{ freespace_allocation_device }} to create a partition"
