---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install debootstrap
  ansible.builtin.apt:
    name: debootstrap
    state: present
    install_recommends: false

- name: Create tmproot directory
  ansible.builtin.file:
    path: "{{ partition_tmproot }}"
    state: directory

- name: Mount tmproot
  ansible.builtin.mount:
    path: "{{ partition_tmproot }}"
    src: none
    fstype: tmpfs
    state: mounted

- name: Bootstrap tmproot
  ansible.builtin.command: |
    debootstrap --variant=minbase bullseye {{ partition_tmproot }} https://deb.debian.org/debian/
  args:
    creates: "{{ partition_tmproot }}/bin"

- name: Create tmproot mountpoints
  ansible.builtin.file:
    path: "{{ partition_tmproot }}/{{ item }}"
    state: directory
  loop:
    - mnt
    - mnt/root
    - root
    - root/.ssh

- name: Copy ssh keys
  ansible.builtin.copy:
    src: /root/.ssh/authorized_keys
    dest: "{{ partition_tmproot }}/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: 0600
    remote_src: true

- name: Get systemd running sockets
  ansible.builtin.shell: |
    systemctl | grep running | grep socket | awk '{print $1}'
  changed_when: false
  register: systemd_sockets

- name: Stop systemd running sockets
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  loop: "{{ systemd_sockets.stdout_lines }}"

- name: Get systemd running services
  ansible.builtin.shell: |
    systemctl | grep running | grep service | grep -v 'ssh.service' | awk '{print $1}'
  changed_when: false
  register: systemd_services

- name: Stop systemd running services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  loop: "{{ systemd_services.stdout_lines }}"

- name: Get systemd running timers
  ansible.builtin.shell: systemctl | grep running | grep timer | awk '{print $1}'
  changed_when: false
  register: systemd_timers

- name: Stop systemd running timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  loop: "{{ systemd_timers.stdout_lines }}"

- name: Pivot root and temporary root
  ansible.builtin.shell: |
    set -e
    touch {{ partition_tmproot }}/var/lock/tmproot

    mount --make-rprivate /
    pivot_root {{ partition_tmproot }} {{ partition_tmproot }}/mnt/root
    for i in dev proc sys run; do mount --move /mnt/root/$i /$i; done

    apt-get update && apt-get install -yq --no-install-recommends lsof systemd openssh-server python3
    systemctl restart sshd
    systemctl daemon-reexec

- name: Wait for SSH connection
  ansible.builtin.wait_for_connection:
    delay: 5
    timeout: 60

- name: Reset SSH connection
  ansible.builtin.meta: reset_connection
