---
- name: Terminate blocking processes
  ansible.builtin.shell: |
    for i in $(lsof | grep /oldroot | awk '{print $2}' | sort -u); do kill -9 $i; done
  changed_when: false

- name: Wait for blocking processes to terminate
  ansible.builtin.pause:
    seconds: 5

- name: Unmount root (efi)
  ansible.builtin.mount:
    path: /mnt/root/boot/efi
    state: unmounted
  ignore_errors: true

- name: Unmount root
  ansible.builtin.mount:
    path: /mnt/root
    state: unmounted
  ignore_errors: true

- name: Wait for root to unmount
  ansible.builtin.wait_for:
    path: /mnt/root/bin
    state: absent
    timeout: 15
