---
- name: Mount root partition
  ansible.posix.mount:
    path: /mnt/root
    src: "{{ partition_volume }}"
    fstype: ext4
    state: mounted
    opts: defaults
  become: true
  become_user: root
  tags: [ partition, mount ]

- name: Pivot root and temorary root
  ansible.builtin.shell: |
    set -euo pipefail

    mount --make-rprivate /
    pivot_root /mnt/root /mnt/root/{{ partition_tmproot }}
    for i in dev proc sys run; do mount --move {{ partition_tmproot }}/$i /$i; done
    rm /var/lock/tmproot

    systemctl restart sshd
    systemctl daemon-reexec
  args:
    executable: /bin/bash
  changed_when: false

- name: Wait for SSH connection
  ansible.builtin.wait_for_connection:
    delay: 5
    timeout: 60

- name: Reset SSH connection
  ansible.builtin.meta: reset_connection

- name: Unmount temporary root
  ansible.posix.mount:
    path: "{{ partition_tmproot }}"
    state: unmounted

- name: Mount present filesystems
  ansible.builtin.shell: |
    set -euo pipefail
    mount -a
    mount --make-rshared /
  args:
    executable: /bin/bash
  changed_when: false

- name: Restart systemd failed service  # noqa: command-instead-of-module
  ansible.builtin.shell: |
    set -euo pipefail
    systemctl | ( grep 'failed' || true ) | awk '{ print $2 }' | xargs systemctl restart
  args:
    executable: /bin/bash
  changed_when: false

- name: Start systemd services  # noqa: command-instead-of-module
  ansible.builtin.command: systemctl isolate default.target
  changed_when: false
