---
- name: Mount root partition
  mount:
    path: /mnt/root
    src: "{{ partition_volume }}"
    fstype: ext4
    state: mounted
    opts: defaults
  become: true
  become_user: root
  tags: [ partition, mount ]

- name:
  ansible.builtin.shell: |
    set -e

    mount --make-rprivate /
    pivot_root /mnt/root /mnt/root/{{ partition_tmproot }}
    for i in dev proc sys run; do mount --move {{ partition_tmproot }}/$i /$i; done

    systemctl restart sshd
    systemctl daemon-reexec

- name: Wait for SSH connection
  ansible.builtin.wait_for_connection:
    delay: 5
    timeout: 60

- name: Reset SSH connection
  ansible.builtin.meta: reset_connection

- name: Unmount temporary root
  mount:
    path: "{{ partition_tmproot }}"
    state: unmounted

- name: mount -a
  ansible.builtin.shell: mount -a

- name: Restart systemd failed service
  ansible.builtin.shell: |
    systemctl | grep failed | awk '{ print $2 }' | xargs systemctl restart
  changed_when: false

- name: mount --make-rshared /
  ansible.builtin.shell: mount --make-rshared /

- name: systemctl isolate default.target
  ansible.builtin.shell: systemctl isolate default.target
