---
- name: set tmproot state
  ansible.builtin.stat:
    path: /var/lock/tmproot
  register: tmproot

- name: include tmproot
  include_tasks: 00-tmproot.yml
  when: not tmproot.stat.exists

- name: set oldroot state
  ansible.builtin.stat:
    path: /oldroot/bin
  register: oldroot

- name: include unmount
  include_tasks: 01-unmount.yml
  when: oldroot.stat.exists

- name: reset tmproot state
  ansible.builtin.stat:
    path: /var/lock/tmproot
  register: tmproot

- name: assert tmproot state
  ansible.builtin.assert:
    that:
      - tmproot.stat.exists
    fail_msg: "tmproot does not exist"
    success_msg: "tmproot exists"

- include_tasks: 02-resize.yml
