---
- name: Set tmproot path
  ansible.builtin.set_fact:
    partition_tmproot: "/mnt/tmproot{{ partition_volume.replace('/', '-') }}"

- name: Get tmproot state
  ansible.builtin.stat:
    path: /var/lock/tmproot
  register: tmproot

- name: Setup temporary root
  ansible.builtin.include_tasks: 00-tmproot.yml
  when: not tmproot.stat.exists

- name: Get root state
  ansible.builtin.stat:
    path: /mnt/root/bin
  register: root

- name: Unmount root
  ansible.builtin.include_tasks: 01-unmount.yml
  when: root.stat.exists

- name: Get tmproot state
  ansible.builtin.stat:
    path: /var/lock/tmproot
  register: tmproot

- name: Assert tmproot state
  ansible.builtin.assert:
    that:
      - tmproot.stat.exists
    fail_msg: "temporary root is not mounted"
    success_msg: "temporary root is mounted"

- name: Get root state
  ansible.builtin.stat:
    path: /mnt/root/bin
  register: root

- name: Assert root state
  ansible.builtin.assert:
    that:
      - not root.stat.exists
    fail_msg: "root is mounted"
    success_msg: "root is not mounted"

- name: Partition volume
  ansible.builtin.include_tasks: 02-partition.yml

- name: Mount root partition
  ansible.builtin.include_tasks: 03-mount.yml
