---
- name: Set tmproot path
  ansible.builtin.set_fact:
    partition_tmproot: "/mnt/tmproot{{ partition_volume.replace('/', '-') }}"

- name: Get tmproot state
  ansible.builtin.stat:
    path: /var/lock/tmproot
  register: tmproot

- name: Setup temporary root
  include_tasks: 00-tmproot.yml
  when: not tmproot.stat.exists

- name: Get root state
  ansible.builtin.stat:
    path: /mnt/root/bin
  register: root

- name: Unmount root
  include_tasks: 01-unmount.yml
  when: root.stat.exists

- name: reset tmproot state
  ansible.builtin.stat:
    path: /var/lock/tmproot
  register: tmproot

- name: assert tmproot state
  ansible.builtin.assert:
    that:
      - tmproot.stat.exists
    fail_msg: "tmproot does not exist"
    success_msg: "tmproot exists"

- include_tasks: 02-resize.yml
