---
- name: Set tmproot path
  ansible.builtin.set_fact:
    partition_tmproot: "/mnt/tmproot{{ partition_volume.replace('/', '-') }}"

- name: Get tmproot state
  ansible.builtin.stat:
    path: /var/lock/tmproot
  register: partition_state_tmproot

- name: Setup temporary root
  ansible.builtin.include_tasks: 00-tmproot.yml
  when: not partition_state_tmproot.stat.exists

- name: Get root state
  ansible.builtin.stat:
    path: /mnt/root/bin
  register: partition_state_root

- name: Unmount root
  ansible.builtin.include_tasks: 01-unmount.yml
  when: partition_state_root.stat.exists

- name: Get root state
  ansible.builtin.stat:
    path: /mnt/root/bin
  register: partition_state_root

- name: Handle root partition
  when: not partition_state_root.stat.exists
  block:
    - name: Partition volume
      ansible.builtin.include_tasks: 02-partition.yml

    - name: Mount root partition
      ansible.builtin.include_tasks: 03-mount.yml
