---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: debian-bullseye-arm64
    image: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bullseye/latest/SHA512SUMS
    image_arch: aarch64
    vm_network: vmnet-shared
provisioner:
  name: ansible
  inventory:
    host_vars:
      debian-bullseye-arm64:
        root_filesystem_device: /dev/vdb
        root_filesystem_partition: /dev/vdb1
        root_filesystem_size: 2G
        allocate_freespace_device: /dev/vdb2

        lvm_device: /dev/vdb
verifier:
  name: testinfra
