---
- name: Prepare
  hosts: all
  become: true

  environment:
    http_proxy: "{{ lookup('ansible.builtin.env', 'http_proxy') | default(omit) }}"
    https_proxy: "{{ lookup('ansible.builtin.env', 'https_proxy') | default(omit) }}"

  tasks:
    - name: "Include root_filesystem"
      ansible.builtin.include_role:
        name: "root_filesystem"

    - name: "Include allocate_freespace"
      ansible.builtin.include_role:
        name: "allocate_freespace"
