---
- name: Prepare
  hosts: all
  become: true

  environment:
    http_proxy: "{{ lookup('ansible.builtin.env', 'http_proxy') | default(omit) }}"
    https_proxy: "{{ lookup('ansible.builtin.env', 'https_proxy') | default(omit) }}"

  tasks: []
