---
- name: Converge
  hosts: all
  become: true

  environment:
    http_proxy: "{{ lookup('ansible.builtin.env', 'http_proxy') | default(omit) }}"
    https_proxy: "{{ lookup('ansible.builtin.env', 'https_proxy') | default(omit) }}"

  tasks:
    - name: "Include tmproot_mount"
      ansible.builtin.include_role:
        name: "tmproot_mount"
