---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: debian-bookworm-amd64
    image_url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bookworm/latest/SHA512SUMS
    network_ssh_port: 2222
provisioner:
  name: ansible
verifier:
  name: testinfra
