---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: debian-bookworm-arm64
    image_arch: aarch64
    image_url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-arm64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bookworm/latest/SHA512SUMS
    network_mode: vmnet-shared
    vm_memory: 2048
provisioner:
  name: ansible
verifier:
  name: testinfra
