---
- name: Assert inventory variables
  ansible.builtin.assert:
    that:
      - root_filesystem_device is defined
      - root_filesystem_device is match('^/dev/\w+$')
      - root_filesystem_partition is defined
      - root_filesystem_partition is match('^/dev/\w+$')
      - root_filesystem_size is defined
      - root_filesystem_size is match('^\d+G$')

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install fdisk
  ansible.builtin.apt:
    name: fdisk
    state: present
    install_recommends: false

- name: Get current number of blocks in volume
  ansible.builtin.shell: |
    set -euo pipefail
    fdisk -l {{ root_filesystem_partition }} | grep 'Disk' | awk '{ print $7 }'
  args:
    executable: /bin/bash
  register: root_filesystem_sectors_current
  changed_when: false

- name: Set desired number of blocks in volume
  ansible.builtin.set_fact:
    root_filesystem_sectors_current: "{{ root_filesystem_sectors_current.stdout | int }}"
    root_filesystem_sectors_desired: "{{ (root_filesystem_size.replace('G', '') | int * 1024 * 1024 * 1024 / 512) | int }}"

- name: Process root filesystem partition
  ansible.builtin.include_tasks: process.yml
  when: root_filesystem_sectors_current | int != root_filesystem_sectors_desired | int
