---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install LVM
  ansible.builtin.apt:
    name: lvm2
    state: present
    install_recommends: false

- name: Check if PV exists
  command: pvs {{ lvm_physical_volume }} --noheadings
  register: lvm_pvs
  failed_when: false
  changed_when: false

- name: Create PV
  command: pvcreate {{ lvm_physical_volume }}
  when: lvm_pvs.rc != 0

- name: Create VG
  community.general.lvg:
    vg: "{{ lvm_volume_group }}"
    pvs: "{{ lvm_physical_volume }}"

- name: Create LV
  community.general.lvol:
    vg: "{{ lvm_volume_group }}"
    lv: "{{ lvm_logical_volume }}"
    size: "{{ lvm_logical_volume_size }}"
    state: present
